### ISSUE TITLE
Trying to renew in Google Cloud DNS

### ISSUE THREAD

**Issue by jmpenalosa** [rmbolger/Posh-ACME#270]
Hi,

I'm getting this error when trying to run updating certificates using the UI installed in a Windows Box.

I did specify the path of the json file in the UI as well, but it doesn't seem to work. It cannot update the DNS record.

2020-08-07 11:56:09.808 -04:00 [INF] DNS: Creating TXT Record '_acme-challenge.*editedthisforpost*.net' with value 'gu80zY7wEEO5TDiTroy5tSoye7MwV_8EGK1_QjjfRUw', in Zone Id '' using API provider 'Powershell/PoshACME DNS'

2020-08-07 11:56:10.026 -04:00 [ERR] DNS update failed: Powershell/PoshACME DNS :: Error - ParameterBindingValidationException: Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at System.Management.Automation.ParameterBinderController.BindPositionalParametersInSet(UInt32 validParameterSets, Dictionary`2 nextPositionalParameters, CommandParameterInternal argument, ParameterBindingFlags flags, ParameterBindingException& bindingException)
   at System.Management.Automation.ParameterBinderController.BindPositionalParameters(Collection`1 unboundArguments, UInt32 validParameterSets, UInt32 defaultParameterSet, ParameterBindingException& outgoingBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)

**Comment by rmbolger** [comment]
It sounds like you might be using Certify the Web rather than Posh-ACME directly. Let's ping @webprofusion-chrisc and see if he has any thoughts.G

**Comment by jmpenalosa** [comment]
@rmbolger @webprofusion-chrisc 

Yes I am. Thank you.

**Comment by webprofusion-chrisc** [comment]
Moving discussion to https://github.com/webprofusion/certify/issues/517

**Comment by rmbolger** [comment]
Looks like this got solved over there. Nice work folks!
